
spring:
  devtools:
    livereload:
      enable: true
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1q2w3e!Q@W#E
  jpa:
    properties:
      hibernate:
        format_sql: true
        sql_show: true
        use_sql_comments: true
        ddl-auto: none
    generate-ddl: false
    show-sql: true
  # 이미지 업로드를 위한 설정
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: c:/temp
      max-file-size: 200MB
      max-request-size: 200MB

#cors setting
cors:
  origins:
    http://localhost:8080,
# Log
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
            BasicBinder: trace
      apache:
        commons:
          beanutils: error
  file:
    name: ./logs/login-local.log

